### ISSUE TITLE
C2M2 Planning Doc

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/crosscut-metadata#24]
Draft a one-page document to cover design and organizational issues for the C2M2 (modelling) focus area.

**Comment by abradyIGS** [comment]
conferred with @RLC-DCPPC ; creating a c2m2 planning statement for this sprint would be obsolete, since our work for this phase is done and summarized [here](https://docs.google.com/document/d/1-Ef1iW772QFo_XScoxlH1NU91kpH3Vcgeazss-EMP-c).

closing: will create c2m2 planning statement for next sprint (from §3 in the linked summary report) after Halloween.
